### ISSUE TITLE
Move relevant code to a new class for detecting objects

### ISSUE THREAD

**Issue by Myla-Kelly** [FROG3160/2024-crescendo#22]
https://github.com/FROG3160/2024-crescendo/blob/145e2c7a712961947c31d00a9cc2d6b8989089d9/roborio-src/subsystems/vision.py#L16

**Comment by celttechie** [comment]
All of the code from last year pertaining to detecting objects and calculating drive movement needs to be moved to this new class.  We aren't using limelight for AprilTags this year, so the other code can be removed.
