### ISSUE TITLE
Add intake roller, intake wheel and transfer wheel motor controllers to Intake class.

### ISSUE THREAD

**Issue by celttechie** [FROG3160/2024-crescendo#42]
Add the 3 motor controllers to the __init__ of Intake.

Github link:
https://github.com/FROG3160/2024-crescendo/blob/d477279a5db7c80c079d811e3ec8f8220fbb2d7b/roborio-src/subsystems/intake.py#L5-L7

GitLens link: 
https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci84OTk4ZjFiMDViOTAzZWU3MmY1MjM3YTY3MDgzOWY0OTM2ZTdiNGE1L2Yvcm9ib3Jpby1zcmMvc3Vic3lzdGVtcy9pbnRha2UucHk%2FdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViLmNvbSUyRkZST0czMTYwJTJGMjAyNC1jcmVzY2VuZG8uZ2l0JmxpbmVzPTUtNw%3D%3D?origin=gitlens

**Comment by Joseph3160** [comment]
Currently at school without GLARE computer. Will start working at 4:07
